---
title: "NYC Open Data"
author: "Steven Lawrence"
date: "November 19, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install.packages("RSocrata")
#devtools::install_github("Chicago/RSocrata")
library(RSocrata)
library(tidyverse)

```

```{r}

token <- "QsuUJQpyjGciXV5KibPhY64hO"
```

```{r}

brooklyn<-RSocrata::read.socrata(
    url="https://data.cityofnewyork.us/resource/erm2-nwe9.csv?borough=BROOKLYN&select=$group_by=incident_zip&$limit=1000", 
    app_token = token) 

brooklyn %>% pull(borough) %>% head()

dim(brooklyn)

```

```{r}

manhattan<-RSocrata::read.socrata(url="https://data.cityofnewyork.us/resource/erm2-nwe9.csv?borough=MAnhattan", app_token = token) 

dim(manhattan)

```

```{r}
nyc_311_data<-RSocrata::read.socrata(url="https://data.cityofnewyork.us/resource/erm2-nwe9.csv?$select=borough$group=incident_zip&$limit=1000", 
                                     app_token = token
                                    ) 

dim(nyc_311_data)

nyc_311_data %>% pull(borough) %>% table()
```

