<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Ava Hamilton" />


<title>regression_analysis</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/sandstone.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 61px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 66px;
  margin-top: -66px;
}
.section h2 {
  padding-top: 66px;
  margin-top: -66px;
}
.section h3 {
  padding-top: 66px;
  margin-top: -66px;
}
.section h4 {
  padding-top: 66px;
  margin-top: -66px;
}
.section h5 {
  padding-top: 66px;
  margin-top: -66px;
}
.section h6 {
  padding-top: 66px;
  margin-top: -66px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Team 4 - Final Project</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Overview</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="mailto:&lt;jpb2210@cumc.columbia.edu&gt;">
    <span class="fa fa-envelope fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="https://github.com/jpb2210/p8105_final_project">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">regression_analysis</h1>
<h4 class="author">Ava Hamilton</h4>
<h4 class="date">12/1/2019</h4>

</div>


<div id="read-in-data" class="section level2">
<h2>read in data</h2>
<pre class="r"><code>nyc &lt;- read_csv(file = &quot;../p8105nyc_311_100k.csv&quot;) %&gt;% 
    janitor::clean_names()</code></pre>
<pre><code>## Warning: 13949 parsing failures.
##    row                   col           expected                        actual                       file
## 100085 taxi_pick_up_location 1/0/T/F/TRUE/FALSE WEST   50 STREET AND BROADWAY &#39;../p8105nyc_311_100k.csv&#39;
## 100150 taxi_pick_up_location 1/0/T/F/TRUE/FALSE JFK Airport                   &#39;../p8105nyc_311_100k.csv&#39;
## 100172 taxi_pick_up_location 1/0/T/F/TRUE/FALSE 625 EAST 14 STREET MANHATTAN  &#39;../p8105nyc_311_100k.csv&#39;
## 100215 taxi_pick_up_location 1/0/T/F/TRUE/FALSE Other                         &#39;../p8105nyc_311_100k.csv&#39;
## 100268 taxi_pick_up_location 1/0/T/F/TRUE/FALSE Other                         &#39;../p8105nyc_311_100k.csv&#39;
## ...... ..................... .................. ............................. ..........................
## See problems(...) for more details.</code></pre>
<pre class="r"><code>nyc_tidy &lt;- nyc %&gt;%   
    filter(borough != &quot;Unspecified&quot;) %&gt;% 
    separate(closed_date, 
             into = c(&quot;closed_month&quot;,&quot;closed_day&quot;,&quot;closed_year&quot;), 
             sep = &quot;\\/&quot; ) %&gt;%
    separate(closed_year, 
             into = c(&quot;closed_year&quot;,&quot;closed_time&quot;), 
             sep = &quot; &quot;) %&gt;% 
    mutate(
        created_year = as.numeric(created_year),
        created_month = as.numeric(created_month),
        created_day = as.numeric(created_day),
        city = as.factor(city),
        status = as.factor(status),
        borough = as.factor(borough),
        agency = as.factor(agency),
        complaint_type = as.factor(complaint_type),
        community_board = as.factor(community_board),
        open_complaint = ifelse(status == &quot;Closed&quot;, yes = 0, no = 1),
        # open_complaint = ifelse(is.na(closed_year),  yes = 1, no = 0),
        complaint_simp = case_when(
            str_detect(complaint_type, 
                       regex(&quot;street&quot;, ignore_case = TRUE))
            |str_detect(complaint_type, 
                        regex(&quot;sidewalk&quot;, ignore_case = TRUE))
            |str_detect(complaint_type, 
                        regex(&quot;curb&quot;, ignore_case = TRUE)) ~ &quot;Street Condition&quot;,
            str_detect(complaint_type, 
                       regex(&quot;noise&quot;, ignore_case = TRUE)) ~ &quot;Noise&quot;,
            str_detect(complaint_type, 
                       regex(&quot;heat&quot;, ignore_case = TRUE)) ~ &quot;Heat&quot;,
            str_detect(complaint_type, 
                       regex(&quot;water&quot;, ignore_case = TRUE))
            |str_detect(complaint_type, 
                        regex(&quot;leak&quot;, ignore_case = TRUE))
            |str_detect(complaint_type, 
                        regex(&quot;plumbing&quot;, ignore_case = TRUE))
            |str_detect(complaint_type, 
                        regex(&quot;boiler&quot;, ignore_case = TRUE)) ~ &quot;Water/plumbing&quot;,
            str_detect(complaint_type, 
                       regex(&quot;paint&quot;, ignore_case = TRUE)) ~ &quot;Paint/Plaster&quot;,
            str_detect(complaint_type, 
                       regex(&quot;asbestos&quot;, ignore_case = TRUE))
            |str_detect(complaint_type, 
                        regex(&quot;lead&quot;, ignore_case = TRUE))
            |str_detect(complaint_type, 
                        regex(&quot;hazard&quot;, ignore_case = TRUE))
            |str_detect(complaint_type, 
                        regex(&quot;mold&quot;, ignore_case = TRUE)) ~ &quot;Hazard Material&quot;,
            str_detect(complaint_type, 
                       regex(&quot;elevator&quot;, ignore_case = TRUE)) 
            |str_detect(complaint_type, 
                        regex(&quot;maintenance&quot;, ignore_case = TRUE))
            |str_detect(complaint_type, 
                        regex(&quot;electric&quot;, ignore_case = TRUE))
            |str_detect(complaint_type, 
                        regex(&quot;stairs&quot;, ignore_case = TRUE))
            |str_detect(complaint_type, 
                        regex(&quot;window&quot;, ignore_case = TRUE)) 
            |str_detect(complaint_type, 
                        regex(&quot;appliance&quot;, ignore_case = TRUE)) ~ &quot;Maintenance&quot;,
            str_detect(complaint_type, 
                       regex(&quot;sanita&quot;, ignore_case = TRUE))
            |str_detect(complaint_type, 
                        regex(&quot;rodent&quot;, ignore_case = TRUE))
            |str_detect(complaint_type, 
                        regex(&quot;dirty&quot;, ignore_case = TRUE))
            |str_detect(complaint_type, 
                        regex(&quot;sew&quot;, ignore_case = TRUE))
            |str_detect(complaint_type, 
                        regex(&quot;standing water&quot;, ignore_case = TRUE)) ~ &quot;Sanitation&quot;,
            str_detect(complaint_type, 
                       regex(&quot;tree&quot;, ignore_case = TRUE)) ~ &quot;Tree&quot;,
            str_detect(complaint_type, 
                       regex(&quot;parking&quot;, ignore_case = TRUE))
            |str_detect(complaint_type, 
                        regex(&quot;car&quot;, ignore_case = TRUE))
            |str_detect(complaint_type, 
                        regex(&quot;drive&quot;, ignore_case = TRUE))
            |str_detect(complaint_type,  
                        regex(&quot;vehicle&quot;, ignore_case = TRUE))
            |str_detect(complaint_type,  
                        regex(&quot;traffic&quot;, ignore_case = TRUE)) ~ &quot;Car/Traffic&quot;,
            str_detect(complaint_type, 
                       regex(&quot;air&quot;, ignore_case = TRUE)) ~ &quot;Air Quality&quot;,
            str_detect(complaint_type, 
                       regex(&quot;collection&quot;, ignore_case = TRUE)) ~ &quot;Collection&quot;,
            str_detect(complaint_type, 
                       regex(&quot;homeless&quot;, ignore_case = TRUE))
            |str_detect(complaint_type, 
                        regex(&quot;panhandling&quot;, ignore_case = TRUE)) ~ &quot;Homeless&quot;),
        health_complaint = ifelse(
            complaint_simp %in% c(&quot;Heat&quot;, &quot;Water/Plumbing&quot;, &quot;Hazard Material&quot;, &quot;Sanitation&quot;, &quot;Air Quality&quot;), yes = 1, no = 0),
        complaint_simp = as.factor(complaint_simp),
        open_health_complaint = case_when(
            open_complaint == 1 &amp; health_complaint == 1 ~ 1,
            open_complaint == 0 | health_complaint == 0 ~ 0
        ),
        # openCorr = ifelse(status == &quot;Closed&quot;, yes = 0, no = 1),
        status = as.factor(status)
    )</code></pre>
<pre><code>## Warning: Expected 2 pieces. Additional pieces discarded in 489924 rows [1,
## 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 16, 17, 18, 20, 21, 22, ...].</code></pre>
<p>Adding community district data</p>
<pre class="r"><code>inc_df = read_csv(&quot;./Med_income_2017.csv&quot;) %&gt;% 
    janitor::clean_names() %&gt;% 
    mutate(
        pop_1000s = round(total_population/1000, 0),
        inc_1000s = round(median_income/1000, 1),
        income_bracket = case_when(
            median_income &gt;= 20000 &amp; median_income &lt;= 30000 ~ &quot;20k-30k&quot;,
            median_income &gt; 30000 &amp; median_income &lt;= 40000 ~ &quot;30-40k&quot;,
            median_income &gt; 40000 &amp; median_income &lt;= 50000 ~ &quot;40-50k&quot;,
            median_income &gt; 50000 &amp; median_income &lt;= 60000 ~ &quot;50-60k&quot;,
            median_income &gt; 60000 &amp; median_income &lt;= 70000 ~ &quot;60-70k&quot;,
            median_income &gt; 70000 &amp; median_income &lt;= 80000 ~ &quot;70-80k&quot;,
            median_income &gt; 80000 &amp; median_income &lt;= 90000 ~ &quot;80-90k&quot;,
            median_income &gt; 90000 &amp; median_income &lt;= 100000 ~ &quot;90-100k&quot;,
            median_income &gt; 100000 &amp; median_income &lt;= 125000 ~ &quot;100-125k&quot;,
            median_income &gt; 125000 &amp; median_income &lt;= 150000 ~ &quot;125k+&quot;,
        ),
        income_bracket = as.factor(income_bracket)
    )

# adding income to data and removing any observations that do not have a specific community board to link to income
add_inc = left_join(nyc_tidy, inc_df, by = &quot;community_board&quot;) %&gt;% 
    filter(is.na(median_income) == FALSE) %&gt;% 
    mutate(
        year_fac = as.factor(created_year)
    )</code></pre>
<pre><code>## Warning: Column `community_board` joining factor and character vector,
## coercing into character vector</code></pre>
<div id="aggregating-data-to-community-district-and-year-level" class="section level3">
<h3>Aggregating data to community district and year level</h3>
<p>To examine the effect of community district level variables on total number of complaints we must first aggregate to the community district level. We are also interested in how year effects the number of complaints in each district so we group by year as well to produce complaint totals for each year and community district.</p>
<p>Once we have complaint totals, we do not want individual complaint information anymore. We select distinct year * community district observations.</p>
<pre class="r"><code># grouping by community district and year
cb_group_year = add_inc %&gt;% 
    group_by(community_board, created_year) %&gt;%
    add_count(community_board, name = &quot;number_complaints&quot;) %&gt;% 
    mutate(
        num_unsolved = sum(open_complaint),
        num_health_complaint = sum(health_complaint),
        num_open_health = sum(open_health_complaint)
    ) %&gt;% 
    select(number_complaints, num_unsolved, num_open_health, everything())


########## including year
cb_group_year_distinct = cb_group_year %&gt;% 
    select(community_board, number_complaints, inc_1000s, num_unsolved, num_health_complaint, borough, per_black_nh, per_hisp, per_white_nh, median_income, num_open_health, created_year, year_fac, pop_1000s) %&gt;% 
    distinct() %&gt;% 
    arrange(community_board) %&gt;% 
    mutate(
        borough = relevel(borough, ref = &quot;MANHATTAN&quot;)
        )

cb_group_year_distinct = within(cb_group_year_distinct, borough &lt;- relevel(borough, ref = &quot;MANHATTAN&quot;))

manhanttan_distinct = cb_group_year_distinct %&gt;% 
    filter(borough == &quot;MANHATTAN&quot;)

brooklyn_distinct = cb_group_year_distinct %&gt;% 
    filter(borough == &quot;BROOKLYN&quot;)

bronx_distinct = cb_group_year_distinct %&gt;% 
    filter(borough == &quot;BRONX&quot;)

queens_distinct = cb_group_year_distinct %&gt;% 
    filter(borough == &quot;QUEENS&quot;)

SI_distinct = cb_group_year_distinct %&gt;% 
    filter(borough == &quot;STATEN ISLAND&quot;)</code></pre>
</div>
</div>
<div id="what-neighborhood-characteristics-effect-number-and-type-of-complaints-in-each-community-district" class="section level2">
<h2>What neighborhood characteristics effect number and type of complaints in each community district?</h2>
<p>We conducted linear models to examine predictors of number of complaints from 2014-2018 per community district. Our three outcomes were:</p>
<ol style="list-style-type: decimal">
<li>Total number of complaints</li>
<li>Number of health complaints</li>
<li>Number of unresolved complaints.</li>
</ol>
<p>We looked at these categories of complaints from 2014-2018 predicted by year, and community district level variables including median income (in the 1000s), total population (in the 1000s), percent non-hispanic black and percent Hispanic. For outcomes 1 and 2 we included number of unresolved complaints as a predictor as well.</p>
<p>As we have equal complaints across borough we startified our analysis to predict number of complaints within each borough.</p>
<div id="number-of-complaints-by-nyc-community-district" class="section level4">
<h4>1) Number of complaints by NYC community district:</h4>
<div id="a-bronx" class="section level5">
<h5><strong>A) Bronx</strong></h5>
<pre class="r"><code># number of complaints
options(scipen = 5)

nom_comp_bronx = lm(number_complaints ~ inc_1000s + num_unsolved + per_black_nh + per_hisp + pop_1000s +created_year, data = bronx_distinct)
summary(nom_comp_bronx)  %&gt;% broom::tidy() %&gt;% knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">-202744.174591</td>
<td align="right">47945.281998</td>
<td align="right">-4.228657</td>
<td align="right">0.0000933</td>
</tr>
<tr class="even">
<td align="left">inc_1000s</td>
<td align="right">-28.726021</td>
<td align="right">12.195282</td>
<td align="right">-2.355503</td>
<td align="right">0.0222307</td>
</tr>
<tr class="odd">
<td align="left">num_unsolved</td>
<td align="right">-4.486933</td>
<td align="right">2.353502</td>
<td align="right">-1.906492</td>
<td align="right">0.0620144</td>
</tr>
<tr class="even">
<td align="left">per_black_nh</td>
<td align="right">-17.477769</td>
<td align="right">9.496429</td>
<td align="right">-1.840457</td>
<td align="right">0.0713027</td>
</tr>
<tr class="odd">
<td align="left">per_hisp</td>
<td align="right">-23.143901</td>
<td align="right">13.319895</td>
<td align="right">-1.737544</td>
<td align="right">0.0880995</td>
</tr>
<tr class="even">
<td align="left">pop_1000s</td>
<td align="right">15.553096</td>
<td align="right">1.070756</td>
<td align="right">14.525340</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left">created_year</td>
<td align="right">101.928668</td>
<td align="right">23.756619</td>
<td align="right">4.290538</td>
<td align="right">0.0000760</td>
</tr>
</tbody>
</table>
<pre class="r"><code>summary(nom_comp_bronx) %&gt;% broom::glance() %&gt;% knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">r.squared</th>
<th align="right">adj.r.squared</th>
<th align="right">sigma</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
<th align="right">df</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0.8310758</td>
<td align="right">0.8119523</td>
<td align="right">236.84</td>
<td align="right">43.45835</td>
<td align="right">0</td>
<td align="right">7</td>
</tr>
</tbody>
</table>
</div>
<div id="b-brooklyn" class="section level5">
<h5><strong>B) Brooklyn</strong></h5>
<pre class="r"><code># Brooklyn
nom_comp_brook = lm(number_complaints ~ inc_1000s + num_unsolved + per_black_nh + per_hisp + pop_1000s +created_year, data = brooklyn_distinct)
summary(nom_comp_brook)  %&gt;% broom::tidy() %&gt;% knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">-190528.955935</td>
<td align="right">31818.4774261</td>
<td align="right">-5.987997</td>
<td align="right">0.0000001</td>
</tr>
<tr class="even">
<td align="left">inc_1000s</td>
<td align="right">2.882396</td>
<td align="right">1.1855879</td>
<td align="right">2.431195</td>
<td align="right">0.0172020</td>
</tr>
<tr class="odd">
<td align="left">num_unsolved</td>
<td align="right">-3.544975</td>
<td align="right">1.4453365</td>
<td align="right">-2.452699</td>
<td align="right">0.0162738</td>
</tr>
<tr class="even">
<td align="left">per_black_nh</td>
<td align="right">4.848914</td>
<td align="right">0.8915716</td>
<td align="right">5.438614</td>
<td align="right">0.0000005</td>
</tr>
<tr class="odd">
<td align="left">per_hisp</td>
<td align="right">4.170561</td>
<td align="right">1.6689790</td>
<td align="right">2.498870</td>
<td align="right">0.0144307</td>
</tr>
<tr class="even">
<td align="left">pop_1000s</td>
<td align="right">6.938757</td>
<td align="right">0.8485194</td>
<td align="right">8.177488</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left">created_year</td>
<td align="right">94.406506</td>
<td align="right">15.7640777</td>
<td align="right">5.988711</td>
<td align="right">0.0000001</td>
</tr>
</tbody>
</table>
<pre class="r"><code>summary(nom_comp_brook) %&gt;% broom::glance() %&gt;% knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">r.squared</th>
<th align="right">adj.r.squared</th>
<th align="right">sigma</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
<th align="right">df</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0.6449032</td>
<td align="right">0.6192335</td>
<td align="right">183.8176</td>
<td align="right">25.12318</td>
<td align="right">0</td>
<td align="right">7</td>
</tr>
</tbody>
</table>
</div>
<div id="c-manhattan" class="section level5">
<h5><strong>C) Manhattan</strong></h5>
<pre class="r"><code># Manhattan

nom_comp_manhattan = lm(number_complaints ~ inc_1000s + num_unsolved + per_black_nh + per_hisp + pop_1000s +created_year, data = manhanttan_distinct)
summary(nom_comp_manhattan)  %&gt;% broom::tidy() %&gt;% knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">53119.003997</td>
<td align="right">64689.6669892</td>
<td align="right">0.8211358</td>
<td align="right">0.4149313</td>
</tr>
<tr class="even">
<td align="left">inc_1000s</td>
<td align="right">2.562733</td>
<td align="right">2.3348619</td>
<td align="right">1.0975950</td>
<td align="right">0.2769173</td>
</tr>
<tr class="odd">
<td align="left">num_unsolved</td>
<td align="right">16.561590</td>
<td align="right">3.5875617</td>
<td align="right">4.6163918</td>
<td align="right">0.0000221</td>
</tr>
<tr class="even">
<td align="left">per_black_nh</td>
<td align="right">1.385217</td>
<td align="right">3.8317954</td>
<td align="right">0.3615061</td>
<td align="right">0.7190348</td>
</tr>
<tr class="odd">
<td align="left">per_hisp</td>
<td align="right">21.377882</td>
<td align="right">4.1291053</td>
<td align="right">5.1773642</td>
<td align="right">0.0000029</td>
</tr>
<tr class="even">
<td align="left">pop_1000s</td>
<td align="right">3.379611</td>
<td align="right">0.8127052</td>
<td align="right">4.1584712</td>
<td align="right">0.0001071</td>
</tr>
<tr class="odd">
<td align="left">created_year</td>
<td align="right">-26.482032</td>
<td align="right">32.1427930</td>
<td align="right">-0.8238871</td>
<td align="right">0.4133789</td>
</tr>
</tbody>
</table>
<pre class="r"><code>summary(nom_comp_manhattan) %&gt;% broom::glance() %&gt;% knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">r.squared</th>
<th align="right">adj.r.squared</th>
<th align="right">sigma</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
<th align="right">df</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0.7021796</td>
<td align="right">0.6713706</td>
<td align="right">305.3685</td>
<td align="right">22.79137</td>
<td align="right">0</td>
<td align="right">7</td>
</tr>
</tbody>
</table>
</div>
<div id="d-queens" class="section level5">
<h5><strong>D) Queens</strong></h5>
<pre class="r"><code># Queens
nom_comp_queens = lm(number_complaints ~ inc_1000s + num_unsolved + per_black_nh + per_hisp + pop_1000s +created_year, data = queens_distinct)
summary(nom_comp_queens)  %&gt;% broom::tidy() %&gt;% knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">-130275.0280769</td>
<td align="right">34097.2062606</td>
<td align="right">-3.8206951</td>
<td align="right">0.0003070</td>
</tr>
<tr class="even">
<td align="left">inc_1000s</td>
<td align="right">-0.4054934</td>
<td align="right">2.6756857</td>
<td align="right">-0.1515475</td>
<td align="right">0.8800281</td>
</tr>
<tr class="odd">
<td align="left">num_unsolved</td>
<td align="right">8.0661850</td>
<td align="right">1.1453378</td>
<td align="right">7.0426251</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">per_black_nh</td>
<td align="right">-5.0760521</td>
<td align="right">1.4045824</td>
<td align="right">-3.6139225</td>
<td align="right">0.0005998</td>
</tr>
<tr class="odd">
<td align="left">per_hisp</td>
<td align="right">0.3088721</td>
<td align="right">1.6961179</td>
<td align="right">0.1821053</td>
<td align="right">0.8560848</td>
</tr>
<tr class="even">
<td align="left">pop_1000s</td>
<td align="right">4.6019048</td>
<td align="right">0.7623587</td>
<td align="right">6.0364040</td>
<td align="right">0.0000001</td>
</tr>
<tr class="odd">
<td align="left">created_year</td>
<td align="right">64.7110298</td>
<td align="right">16.9056988</td>
<td align="right">3.8277643</td>
<td align="right">0.0002999</td>
</tr>
</tbody>
</table>
<pre class="r"><code>summary(nom_comp_queens) %&gt;% broom::glance() %&gt;% knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">r.squared</th>
<th align="right">adj.r.squared</th>
<th align="right">sigma</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
<th align="right">df</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0.8308769</td>
<td align="right">0.8147699</td>
<td align="right">182.1941</td>
<td align="right">51.58495</td>
<td align="right">0</td>
<td align="right">7</td>
</tr>
</tbody>
</table>
</div>
<div id="e-staten-island" class="section level5">
<h5><strong>E) Staten Island</strong></h5>
<pre class="r"><code># SI
nom_comp_SI = lm(number_complaints ~ inc_1000s + num_unsolved + per_black_nh +created_year, data = SI_distinct)
summary(nom_comp_SI)  %&gt;% broom::tidy() %&gt;% knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">-1328232.051623</td>
<td align="right">131138.704917</td>
<td align="right">-10.128452</td>
<td align="right">0.0000014</td>
</tr>
<tr class="even">
<td align="left">inc_1000s</td>
<td align="right">105.342625</td>
<td align="right">25.436644</td>
<td align="right">4.141373</td>
<td align="right">0.0020074</td>
</tr>
<tr class="odd">
<td align="left">num_unsolved</td>
<td align="right">3.786141</td>
<td align="right">2.269629</td>
<td align="right">1.668176</td>
<td align="right">0.1262426</td>
</tr>
<tr class="even">
<td align="left">per_black_nh</td>
<td align="right">257.458351</td>
<td align="right">38.185243</td>
<td align="right">6.742352</td>
<td align="right">0.0000509</td>
</tr>
<tr class="odd">
<td align="left">created_year</td>
<td align="right">656.403425</td>
<td align="right">65.025563</td>
<td align="right">10.094544</td>
<td align="right">0.0000015</td>
</tr>
</tbody>
</table>
<pre class="r"><code>summary(nom_comp_SI) %&gt;% broom::glance() %&gt;% knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">r.squared</th>
<th align="right">adj.r.squared</th>
<th align="right">sigma</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
<th align="right">df</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0.9660939</td>
<td align="right">0.9525315</td>
<td align="right">354.0233</td>
<td align="right">71.23303</td>
<td align="right">0.0000003</td>
<td align="right">5</td>
</tr>
</tbody>
</table>
</div>
<div id="residuals" class="section level5">
<h5><strong>Residuals</strong></h5>
<pre class="r"><code>par(mfrow = c(2,3))
plot(nom_comp_bronx, which = 1, main = &quot;Bronx
&quot;)
plot(nom_comp_brook, which = 1, main = &quot;Brooklyn
&quot;)
plot(nom_comp_manhattan, which = 1, main = &quot;Manhattan
&quot;)
plot(nom_comp_queens, which = 1, main = &quot;Queens
&quot;)
plot(nom_comp_SI, which = 1, main = &quot;Staten Island
&quot;)</code></pre>
<p><img src="regression_analysis_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p><em>Comments:</em></p>
<p>The total number of complaints in each borough significantly predicted by year, borough and CD number of unsolved complaints, percent Hispanic, and population total.</p>
<p>In the Bronx, on average, for each additional year we see 102 more complaints in each community district, for each additional 1000 people in a CD we see 16 more complaints, and for each $1000 increase in median income we see 29 <em><em>fewer</em></em> complaints.</p>
<p>Based on the adjusted R-squared values, number of complaints in a CD range from 67.14% in Manhattan to 95.25% in Staten Island predicted by this combination of variables. Residuals appear to follow normal distributions.</p>
</div>
</div>
<div id="number-of-health-related-complaints-by-nyc-community-district" class="section level4">
<h4>2) Number of health-related complaints by NYC community district:</h4>
<div id="a-bronx-1" class="section level5">
<h5><strong>A) Bronx</strong></h5>
<pre class="r"><code># number of complaints
options(scipen = 5)

nom_comp_h_bronx = lm(num_health_complaint ~  inc_1000s + num_unsolved + per_black_nh + per_hisp + pop_1000s + created_year, data = bronx_distinct)
summary(nom_comp_h_bronx)  %&gt;% broom::tidy() %&gt;% knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">-30255.412876</td>
<td align="right">20824.2449702</td>
<td align="right">-1.4528936</td>
<td align="right">0.1521486</td>
</tr>
<tr class="even">
<td align="left">inc_1000s</td>
<td align="right">-8.709506</td>
<td align="right">5.2968204</td>
<td align="right">-1.6442895</td>
<td align="right">0.1060359</td>
</tr>
<tr class="odd">
<td align="left">num_unsolved</td>
<td align="right">-2.950688</td>
<td align="right">1.0222049</td>
<td align="right">-2.8865916</td>
<td align="right">0.0056237</td>
</tr>
<tr class="even">
<td align="left">per_black_nh</td>
<td align="right">-5.130822</td>
<td align="right">4.1246179</td>
<td align="right">-1.2439509</td>
<td align="right">0.2189914</td>
</tr>
<tr class="odd">
<td align="left">per_hisp</td>
<td align="right">-5.659464</td>
<td align="right">5.7852775</td>
<td align="right">-0.9782528</td>
<td align="right">0.3323937</td>
</tr>
<tr class="even">
<td align="left">pop_1000s</td>
<td align="right">5.261977</td>
<td align="right">0.4650653</td>
<td align="right">11.3144900</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left">created_year</td>
<td align="right">15.360379</td>
<td align="right">10.3182968</td>
<td align="right">1.4886545</td>
<td align="right">0.1425049</td>
</tr>
</tbody>
</table>
<pre class="r"><code>summary(nom_comp_h_bronx) %&gt;% broom::glance() %&gt;% knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">r.squared</th>
<th align="right">adj.r.squared</th>
<th align="right">sigma</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
<th align="right">df</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0.7290075</td>
<td align="right">0.6983291</td>
<td align="right">102.8676</td>
<td align="right">23.76289</td>
<td align="right">0</td>
<td align="right">7</td>
</tr>
</tbody>
</table>
</div>
<div id="b-brooklyn-1" class="section level5">
<h5><strong>B) Brooklyn</strong></h5>
<pre class="r"><code># Brooklyn
nom_comp_h_brook = lm(num_health_complaint ~ inc_1000s + num_unsolved + per_black_nh + per_hisp + pop_1000s +created_year, data = brooklyn_distinct)
summary(nom_comp_h_brook)  %&gt;% broom::tidy() %&gt;% knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">-23721.7860444</td>
<td align="right">9170.1546766</td>
<td align="right">-2.5868469</td>
<td align="right">0.0114295</td>
</tr>
<tr class="even">
<td align="left">inc_1000s</td>
<td align="right">-0.4270540</td>
<td align="right">0.3416890</td>
<td align="right">-1.2498324</td>
<td align="right">0.2148735</td>
</tr>
<tr class="odd">
<td align="left">num_unsolved</td>
<td align="right">-1.2903665</td>
<td align="right">0.4165491</td>
<td align="right">-3.0977535</td>
<td align="right">0.0026607</td>
</tr>
<tr class="even">
<td align="left">per_black_nh</td>
<td align="right">2.0677844</td>
<td align="right">0.2569529</td>
<td align="right">8.0473290</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left">per_hisp</td>
<td align="right">0.0420508</td>
<td align="right">0.4810034</td>
<td align="right">0.0874232</td>
<td align="right">0.9305457</td>
</tr>
<tr class="even">
<td align="left">pop_1000s</td>
<td align="right">1.4565508</td>
<td align="right">0.2445451</td>
<td align="right">5.9561631</td>
<td align="right">0.0000001</td>
</tr>
<tr class="odd">
<td align="left">created_year</td>
<td align="right">11.7719217</td>
<td align="right">4.5432416</td>
<td align="right">2.5910842</td>
<td align="right">0.0113003</td>
</tr>
</tbody>
</table>
<pre class="r"><code>summary(nom_comp_h_brook) %&gt;% broom::glance() %&gt;% knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">r.squared</th>
<th align="right">adj.r.squared</th>
<th align="right">sigma</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
<th align="right">df</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0.5974558</td>
<td align="right">0.5683562</td>
<td align="right">52.97665</td>
<td align="right">20.53142</td>
<td align="right">0</td>
<td align="right">7</td>
</tr>
</tbody>
</table>
</div>
<div id="c-manhattan-1" class="section level5">
<h5><strong>C) Manhattan</strong></h5>
<pre class="r"><code># Manhattan

nom_comp_h_manhattan = lm(num_health_complaint ~ inc_1000s + num_unsolved + per_black_nh + per_hisp + pop_1000s +created_year, data = manhanttan_distinct)
summary(nom_comp_h_manhattan)  %&gt;% broom::tidy() %&gt;% knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">43868.270608</td>
<td align="right">15711.8636388</td>
<td align="right">2.792048</td>
<td align="right">0.0070814</td>
</tr>
<tr class="even">
<td align="left">inc_1000s</td>
<td align="right">1.515195</td>
<td align="right">0.5670926</td>
<td align="right">2.671866</td>
<td align="right">0.0097757</td>
</tr>
<tr class="odd">
<td align="left">num_unsolved</td>
<td align="right">3.514373</td>
<td align="right">0.8713491</td>
<td align="right">4.033255</td>
<td align="right">0.0001628</td>
</tr>
<tr class="even">
<td align="left">per_black_nh</td>
<td align="right">2.612122</td>
<td align="right">0.9306687</td>
<td align="right">2.806715</td>
<td align="right">0.0068042</td>
</tr>
<tr class="odd">
<td align="left">per_hisp</td>
<td align="right">9.125134</td>
<td align="right">1.0028795</td>
<td align="right">9.098934</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">pop_1000s</td>
<td align="right">1.023100</td>
<td align="right">0.1973903</td>
<td align="right">5.183129</td>
<td align="right">0.0000029</td>
</tr>
<tr class="odd">
<td align="left">created_year</td>
<td align="right">-21.925046</td>
<td align="right">7.8068601</td>
<td align="right">-2.808433</td>
<td align="right">0.0067724</td>
</tr>
</tbody>
</table>
<pre class="r"><code>summary(nom_comp_h_manhattan) %&gt;% broom::glance() %&gt;% knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">r.squared</th>
<th align="right">adj.r.squared</th>
<th align="right">sigma</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
<th align="right">df</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0.8400507</td>
<td align="right">0.8235042</td>
<td align="right">74.16807</td>
<td align="right">50.76914</td>
<td align="right">0</td>
<td align="right">7</td>
</tr>
</tbody>
</table>
</div>
<div id="d-queens-1" class="section level5">
<h5><strong>D) Queens</strong></h5>
<pre class="r"><code># Queens
nom_comp_h_queens = lm(num_health_complaint ~ inc_1000s + num_unsolved + per_black_nh + per_hisp + pop_1000s +created_year, data = queens_distinct)
summary(nom_comp_h_queens)  %&gt;% broom::tidy() %&gt;% knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">-214.7435113</td>
<td align="right">6525.6010917</td>
<td align="right">-0.0329079</td>
<td align="right">0.9738521</td>
</tr>
<tr class="even">
<td align="left">inc_1000s</td>
<td align="right">-2.5797587</td>
<td align="right">0.5120788</td>
<td align="right">-5.0378155</td>
<td align="right">0.0000042</td>
</tr>
<tr class="odd">
<td align="left">num_unsolved</td>
<td align="right">0.8433872</td>
<td align="right">0.2191974</td>
<td align="right">3.8476155</td>
<td align="right">0.0002809</td>
</tr>
<tr class="even">
<td align="left">per_black_nh</td>
<td align="right">1.5011842</td>
<td align="right">0.2688122</td>
<td align="right">5.5845095</td>
<td align="right">0.0000005</td>
</tr>
<tr class="odd">
<td align="left">per_hisp</td>
<td align="right">0.1207657</td>
<td align="right">0.3246069</td>
<td align="right">0.3720366</td>
<td align="right">0.7111141</td>
</tr>
<tr class="even">
<td align="left">pop_1000s</td>
<td align="right">0.4839425</td>
<td align="right">0.1459019</td>
<td align="right">3.3169023</td>
<td align="right">0.0015143</td>
</tr>
<tr class="odd">
<td align="left">created_year</td>
<td align="right">0.2113623</td>
<td align="right">3.2354512</td>
<td align="right">0.0653270</td>
<td align="right">0.9481205</td>
</tr>
</tbody>
</table>
<pre class="r"><code>summary(nom_comp_h_queens) %&gt;% broom::glance() %&gt;% knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">r.squared</th>
<th align="right">adj.r.squared</th>
<th align="right">sigma</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
<th align="right">df</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0.7993284</td>
<td align="right">0.7802168</td>
<td align="right">34.86872</td>
<td align="right">41.8243</td>
<td align="right">0</td>
<td align="right">7</td>
</tr>
</tbody>
</table>
</div>
<div id="e-staten-island-1" class="section level5">
<h5><strong>E) Staten Island</strong></h5>
<pre class="r"><code># SI
nom_comp_h_SI = lm(num_health_complaint ~ inc_1000s + num_unsolved + per_black_nh +created_year, data = SI_distinct)
summary(nom_comp_h_SI)  %&gt;% broom::tidy() %&gt;% knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">-100396.9992255</td>
<td align="right">19522.3932541</td>
<td align="right">-5.1426584</td>
<td align="right">0.0004361</td>
</tr>
<tr class="even">
<td align="left">inc_1000s</td>
<td align="right">17.3222313</td>
<td align="right">3.7867094</td>
<td align="right">4.5744813</td>
<td align="right">0.0010192</td>
</tr>
<tr class="odd">
<td align="left">num_unsolved</td>
<td align="right">0.1986437</td>
<td align="right">0.3378758</td>
<td align="right">0.5879193</td>
<td align="right">0.5696244</td>
</tr>
<tr class="even">
<td align="left">per_black_nh</td>
<td align="right">53.7162474</td>
<td align="right">5.6845713</td>
<td align="right">9.4494808</td>
<td align="right">0.0000027</td>
</tr>
<tr class="odd">
<td align="left">created_year</td>
<td align="right">49.3442498</td>
<td align="right">9.6802436</td>
<td align="right">5.0974182</td>
<td align="right">0.0004658</td>
</tr>
</tbody>
</table>
<pre class="r"><code>summary(nom_comp_h_SI) %&gt;% broom::glance() %&gt;% knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">r.squared</th>
<th align="right">adj.r.squared</th>
<th align="right">sigma</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
<th align="right">df</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0.978647</td>
<td align="right">0.9701058</td>
<td align="right">52.70284</td>
<td align="right">114.5795</td>
<td align="right">0</td>
<td align="right">5</td>
</tr>
</tbody>
</table>
</div>
<div id="residuals-1" class="section level5">
<h5><strong>Residuals</strong></h5>
<pre class="r"><code>par(mfrow = c(2,3))
plot(nom_comp_h_bronx, which = 1, main = &quot;Bronx
&quot;)
plot(nom_comp_h_brook, which = 1, main = &quot;Brooklyn
&quot;)
plot(nom_comp_h_manhattan, which = 1, main = &quot;Manhattan
&quot;)
plot(nom_comp_h_queens, which = 1, main = &quot;Queens
&quot;)
plot(nom_comp_h_SI, which = 1, main = &quot;Staten Island
&quot;)</code></pre>
<p><img src="regression_analysis_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<pre class="r"><code># number of health complaints

num_health_model_year = lm(num_health_complaint ~  inc_1000s + num_unsolved + per_black_nh + per_hisp + pop_1000s + borough + created_year, data = cb_group_year_distinct)

summary(num_health_model_year)  %&gt;% broom::tidy() %&gt;% knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">-8271.9050711</td>
<td align="right">9388.3494974</td>
<td align="right">-0.8810819</td>
<td align="right">0.3790056</td>
</tr>
<tr class="even">
<td align="left">inc_1000s</td>
<td align="right">-0.9020550</td>
<td align="right">0.3818616</td>
<td align="right">-2.3622563</td>
<td align="right">0.0188269</td>
</tr>
<tr class="odd">
<td align="left">num_unsolved</td>
<td align="right">0.1332789</td>
<td align="right">0.3175134</td>
<td align="right">0.4197585</td>
<td align="right">0.6749738</td>
</tr>
<tr class="even">
<td align="left">per_black_nh</td>
<td align="right">1.8322552</td>
<td align="right">0.3596117</td>
<td align="right">5.0950935</td>
<td align="right">0.0000006</td>
</tr>
<tr class="odd">
<td align="left">per_hisp</td>
<td align="right">2.8509972</td>
<td align="right">0.5521609</td>
<td align="right">5.1633451</td>
<td align="right">0.0000005</td>
</tr>
<tr class="even">
<td align="left">pop_1000s</td>
<td align="right">1.6639840</td>
<td align="right">0.1776130</td>
<td align="right">9.3685937</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left">boroughBRONX</td>
<td align="right">-18.7226172</td>
<td align="right">25.6646202</td>
<td align="right">-0.7295108</td>
<td align="right">0.4662801</td>
</tr>
<tr class="even">
<td align="left">boroughBROOKLYN</td>
<td align="right">-164.5605905</td>
<td align="right">20.7537174</td>
<td align="right">-7.9292103</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left">boroughQUEENS</td>
<td align="right">-194.1062164</td>
<td align="right">20.7785616</td>
<td align="right">-9.3416580</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">boroughSTATEN ISLAND</td>
<td align="right">523.7213728</td>
<td align="right">95.2839543</td>
<td align="right">5.4964278</td>
<td align="right">0.0000001</td>
</tr>
<tr class="odd">
<td align="left">created_year</td>
<td align="right">4.1343889</td>
<td align="right">4.6559157</td>
<td align="right">0.8879862</td>
<td align="right">0.3752866</td>
</tr>
</tbody>
</table>
<pre class="r"><code>summary(num_health_model_year) %&gt;% broom::glance() %&gt;% knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">r.squared</th>
<th align="right">adj.r.squared</th>
<th align="right">sigma</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
<th align="right">df</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0.7631084</td>
<td align="right">0.7549115</td>
<td align="right">106.907</td>
<td align="right">93.09673</td>
<td align="right">0</td>
<td align="right">11</td>
</tr>
</tbody>
</table>
<pre class="r"><code>par(mfrow = c(2,2))
plot(num_health_model_year)</code></pre>
<p><img src="regression_analysis_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p><em>Comments:</em></p>
<p>Complaints were determined to be health related if they were about heat, hot water, sanitary conditions, poor air quality, or hazardous materials. The total number of health-related complaints is significantly predicted by borough and CD median income, percent non-Hispanic Black and Hispanic, and population total.</p>
<p>On average, for each $1000 increase in median income we see 1 <em><em>fewer</em></em> health related complaints in each community district; for each additional percent of a CD that is black or hispanic we see 2 and 3 more health-related complaints.</p>
<p>Based on the adjusted R-squared value, number of health-related complaints in a CD is 75.49% predicted by this combination of variables. Residuals appear to follow a mostly normal distribution, but there is still room for improvement in model fit, in a later analysis.</p>
</div>
</div>
<div id="number-of-unresolved-complaints-by-nyc-community-district" class="section level4">
<h4>3) Number of unresolved complaints by NYC community district:</h4>
<pre class="r"><code># number of unresolved


num_unsolved_model_year = lm(num_unsolved ~ inc_1000s + per_black_nh + per_hisp + pop_1000s*borough +created_year, data = cb_group_year_distinct)



num_unsolved_model_year = lm(num_unsolved ~ inc_1000s + per_black_nh + per_hisp + pop_1000s*borough +created_year, data = cb_group_year_distinct)

summary(num_unsolved_model_year)  %&gt;% broom::tidy() %&gt;% knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">-10283.6939516</td>
<td align="right">1484.6300047</td>
<td align="right">-6.9267723</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">inc_1000s</td>
<td align="right">0.1630031</td>
<td align="right">0.0639210</td>
<td align="right">2.5500695</td>
<td align="right">0.0112917</td>
</tr>
<tr class="odd">
<td align="left">per_black_nh</td>
<td align="right">0.3082454</td>
<td align="right">0.0594401</td>
<td align="right">5.1858124</td>
<td align="right">0.0000004</td>
</tr>
<tr class="even">
<td align="left">per_hisp</td>
<td align="right">-0.1722722</td>
<td align="right">0.0945901</td>
<td align="right">-1.8212501</td>
<td align="right">0.0696135</td>
</tr>
<tr class="odd">
<td align="left">pop_1000s</td>
<td align="right">0.0780098</td>
<td align="right">0.0438890</td>
<td align="right">1.7774359</td>
<td align="right">0.0765592</td>
</tr>
<tr class="even">
<td align="left">boroughBRONX</td>
<td align="right">-10.2686331</td>
<td align="right">11.5842384</td>
<td align="right">-0.8864314</td>
<td align="right">0.3761298</td>
</tr>
<tr class="odd">
<td align="left">boroughBROOKLYN</td>
<td align="right">-49.2582559</td>
<td align="right">10.1453795</td>
<td align="right">-4.8552403</td>
<td align="right">0.0000020</td>
</tr>
<tr class="even">
<td align="left">boroughQUEENS</td>
<td align="right">-27.9350943</td>
<td align="right">11.0275582</td>
<td align="right">-2.5332076</td>
<td align="right">0.0118369</td>
</tr>
<tr class="odd">
<td align="left">boroughSTATEN ISLAND</td>
<td align="right">16.5121861</td>
<td align="right">48.3313031</td>
<td align="right">0.3416458</td>
<td align="right">0.7328684</td>
</tr>
<tr class="even">
<td align="left">created_year</td>
<td align="right">5.1066667</td>
<td align="right">0.7364082</td>
<td align="right">6.9345599</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left">pop_1000s:boroughBRONX</td>
<td align="right">0.2247090</td>
<td align="right">0.0820453</td>
<td align="right">2.7388414</td>
<td align="right">0.0065527</td>
</tr>
<tr class="even">
<td align="left">pop_1000s:boroughBROOKLYN</td>
<td align="right">0.3708497</td>
<td align="right">0.0675953</td>
<td align="right">5.4863279</td>
<td align="right">0.0000001</td>
</tr>
<tr class="odd">
<td align="left">pop_1000s:boroughQUEENS</td>
<td align="right">0.3130365</td>
<td align="right">0.0680092</td>
<td align="right">4.6028517</td>
<td align="right">0.0000063</td>
</tr>
<tr class="even">
<td align="left">pop_1000s:boroughSTATEN ISLAND</td>
<td align="right">1.7140967</td>
<td align="right">0.3030061</td>
<td align="right">5.6569709</td>
<td align="right">0.0000000</td>
</tr>
</tbody>
</table>
<pre class="r"><code>summary(num_unsolved_model_year) %&gt;% broom::glance() %&gt;% knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">r.squared</th>
<th align="right">adj.r.squared</th>
<th align="right">sigma</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
<th align="right">df</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0.9299737</td>
<td align="right">0.9267907</td>
<td align="right">18.03824</td>
<td align="right">292.1678</td>
<td align="right">0</td>
<td align="right">14</td>
</tr>
</tbody>
</table>
<pre class="r"><code>par(mfrow = c(2,2))
plot(num_unsolved_model_year)</code></pre>
<p><img src="regression_analysis_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p><em>Comments:</em></p>
<p>A complaint was labeled unresolved if its status was not labeled as “closed”. The total number of unresolved complaints is significantly predicted by year of complaint, borough, and CD median income, percent non-Hispanic Black and Hispanic, and population total.</p>
<p>On average, for each additional year we see 5 more unresolved complaints in each community district. The Bronx, Queens, and Staten Island CDs had -10, -28, and 17, more unresolved complaints than manhattan CDs on average, respectively.</p>
<p>Based on the adjusted R-squared value, number of unresolved complaints in a CD are 92.68% predicted by this combination of variables. Residuals appear to follow a normal distribution.</p>
</div>
</div>
<div id="discussion" class="section level2">
<h2>Discussion</h2>
<p>NYC takes in</p>
<p>Based on our descriptive figures, mapped data, and linear models of NYC 311 complaint data, we see that there are a few key factors that play into how types of complaints are dispersed across the city. XX complaints a year,</p>
<p>With XX 311 complaints coming in everyday, a majority of which are closed same day, and 66.5% closed within the week, it is interesting to look into where the open complaints remain.</p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
