---
title: "timeseries"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tseries)
library(forecast)
```

```{r}

new_311 <- nyc_311 %>% 
filter(borough != "Unspecified") %>% 
    mutate(
        year = as.numeric(created_year),
        month = as.numeric(created_month),
        day = as.numeric(created_day),
        city = as.factor(city),
        borough = as.factor(park_borough),
        agency = as.factor(agency),
        complaint_type = as.factor(complaint_type),
        community_board = as.factor(community_board),
        open_complaint = ifelse(is.na(closed_date),  1, 0),
        complaint_simp = case_when(
            str_detect(complaint_type,  regex("street", ignore_case = TRUE))|str_detect(complaint_type,  regex("sidewalk", ignore_case = TRUE))|str_detect(complaint_type,  regex("curb", ignore_case = TRUE))|str_detect(complaint_type,  regex("vehicle", ignore_case = TRUE)) ~ "Street Condition",
            str_detect(complaint_type,  regex("noise", ignore_case = TRUE)) ~ "Noise",
            str_detect(complaint_type, regex("heat", ignore_case = TRUE)) ~ "Heat",
            str_detect(complaint_type, regex("water", ignore_case = TRUE))|str_detect(complaint_type, regex("plumbing", ignore_case = TRUE))|str_detect(complaint_type, regex("boiler", ignore_case = TRUE)) ~ "Water/plumbing",
            str_detect(complaint_type, regex("paint", ignore_case = TRUE)) ~ "Paint/Plaster",
            str_detect(complaint_type, regex("asbestos", ignore_case = TRUE))|str_detect(complaint_type, regex("lead", ignore_case = TRUE))|str_detect(complaint_type, regex("hazard", ignore_case = TRUE)) ~ "Hazard Material",
            str_detect(complaint_type, regex("elevator", ignore_case = TRUE)) ~ "Elevator",
            str_detect(complaint_type, regex("sanita", ignore_case = TRUE))|str_detect(complaint_type, regex("rodent", ignore_case = TRUE))|str_detect(complaint_type, regex("dirty", ignore_case = TRUE)) ~ "Sanitation",
            str_detect(complaint_type, regex("tree", ignore_case = TRUE)) ~ "Tree",
            str_detect(complaint_type, regex("parking", ignore_case = TRUE))|str_detect(complaint_type, regex("car", ignore_case = TRUE))|str_detect(complaint_type, regex("drive", ignore_case = TRUE)) ~ "Car"
        ),
        health_complaint = ifelse(
            complaint_simp %in% c("Heat", "Water/Plumbing", "Hazard Material", "Sanitation"), 1,0),
        complaint_simp = as.factor(complaint_simp)
    )

summary(nycedit$complaint_simp)

nycedit_cb = nycedit %>% 
    group_by(community_board, year) %>%
    add_count(community_board, name = "number_complaints") %>% 
    mutate(
        num_unsolved = sum(open_complaint),
        num_health_complaint = sum(health_complaint)
    ) %>% 
    select(number_complaints, num_unsolved, everything())

head(new_311)

```



```{r}


new_311$agency %>% table()

new_311 %>% 
    select(year, month, complaint_simp, borough, agency) %>% 
    group_by(month, complaint_simp) %>% 
    summarize(
        n = n()
    ) %>% 
    forcats::fct_wxplicit_na() %>% 
    ts() %>% 
    autoplot()
    ggplot(aes(x=month, y = n))+geom_line()
```

